// List of Settings and constants for each subsystem
// Format as #define [SUB_SYSTEM]__[PARAMETER]__[UNIT]
//
// Avoid the use of abbreviations wherever possible
//
// For example:
// #define ENCODER_KNOB__NUMSTEPS 24
// #define ENCODER_KNOB__DISTANCEPERSTEP_MILLIMETERS 1.5
// #define HEATER_PID_LOOP__PROPORTIONAL_GAIN 0.000043


#ifndef _VENTILATOR_CONFIG_H_
#define _VENTILATOR_CONFIG_H_

// System Timings
#pragma region
#define SYSTEM_TIMINGS__STARTUP_DELAY__MILLISECONDS 1000
#define SYSTEM_TIMINGS__DLHR_SENSOR_POLL_TIMEOUT__MILLISECONDS 500
#define SYSTEM_TIMINGS__GUI_UPDATE_PERIOD__MILLISECONDS 50
#define SYSTEM_TIMINGS__GUI_UPDATE_WINDOW__MILLISECONDS 2
#pragma endregion

// Serial Debug Settings
#pragma region
#define SYSTEM__SERIAL_DEBUG__STATEMACHINE false
#define SYSTEM__SERIAL_DEBUG__PRESSURE_TRANSDUCERS true
#define SYSTEM__SERIAL_DEBUG_ENABLED (SYSTEM__SERIAL_DEBUG__STATEMACHINE || SYSTEM__SERIAL_DEBUG__PRESSURE_TRANSDUCERS)
#define SYSTEM__SERIAL_DEBUG__BAUD_RATE 115200
#pragma endregion

// Breath Cycle Default Settings
#pragma region
#define BREATHCYCLE__DEFAULT_PEEP__CENTIMETERSH2O 5.0
#define BREATHCYCLE__DEFAULT_PIP__CENTIMETERSH2O 30.0
#define BREATHCYCLE__DEFAULT_INHALE_DURATION__MILLISECONDS 1000
#define BREATHCYCLE__DEFAULT_INHALE_RAMP_DURATION__MILLISECONDS 500
#define BREATHCYCLE__DEFAULT_EXHALE_DURATION__MILLISECONDS 3000
#define BREATHCYCLE__DEFAULT_CYCLE_DURATION__MILLISECONDS (BREATHCYCLE__DEFAULT_INHALE_DURATION__MILLISECONDS+BREATHCYCLE__DEFAULT_EXHALE_DURATION__MILLISECONDS)
#pragma endregion

// Blower hardware drive settings
#pragma region
#define BLOWER_DRIVER__MIN_PULSE__MICROSECONDS 1000
#define BLOWER_DRIVER__MAX_PULSE__MICROSECONDS 2000
#pragma endregion

// Blower PID Loop settings
#pragma region
#define BLOWER_PID__MIN_CONTROL_OUTPUT 0.00
#define BLOWER_PID__MAX_CONTROL_OUTPUT 100.00
#define BLOWER_PID__CONTROL_DIRECTION DIRECT
#define BLOWER_PID__SAMPLE_TIME 100

#define BLOWER_PID__DEFAULT_PROPORTIONAL_GAIN 0.0000011
#define BLOWER_PID__DEFAULT_INTEGRAL_GAIN     0.00000005
#define BLOWER_PID__DEFAULT_DERIVATIVE_GAIN   0.0000000

#define BLOWER_PID__INHALE_RAMP_PROPORTIONAL_GAIN  BLOWER_PID__DEFAULT_PROPORTIONAL_GAIN
#define BLOWER_PID__INHALE_RAMP_INTEGRAL_GAIN      BLOWER_PID__DEFAULT_INTEGRAL_GAIN
#define BLOWER_PID__INHALE_RAMP_DERIVATIVE_GAIN    BLOWER_PID__DEFAULT_DERIVATIVE_GAIN

#define BLOWER_PID__INHALE_HOLD_PROPORTIONAL_GAIN  BLOWER_PID__DEFAULT_PROPORTIONAL_GAIN
#define BLOWER_PID__INHALE_HOLD_INTEGRAL_GAIN      BLOWER_PID__DEFAULT_INTEGRAL_GAIN
#define BLOWER_PID__INHALE_HOLD_DERIVATIVE_GAIN    BLOWER_PID__DEFAULT_DERIVATIVE_GAIN

#define BLOWER_PID__EXHALE_PROPORTIONAL_GAIN  BLOWER_PID__DEFAULT_PROPORTIONAL_GAIN
#define BLOWER_PID__EXHALE_INTEGRAL_GAIN      BLOWER_PID__DEFAULT_INTEGRAL_GAIN
#define BLOWER_PID__EXHALE_DERIVATIVE_GAIN    BLOWER_PID__DEFAULT_DERIVATIVE_GAIN
#pragma endregion

// Expiration valve hardware driver settings
#pragma region
#define EXPIRATION_VALVE_DRIVER__CLOSED_PULSE__MICROSECONDS 970
#define EXPIRATION_VALVE_DRIVER__OPEN_PULSE__MICROSECONDS 1200
#pragma endregion

// Expiration Valve PID Loop Settings
#pragma region
#define EXPIRATION_VALVE_PID__MIN_CONTROL_OUTPUT 0.00
#define EXPIRATION_VALVE_PID__MAX_CONTROL_OUTPUT 100.00
#define EXPIRATION_VALVE_PID__CONTROL_DIRECTION REVERSE
#define EXPIRATION_VALVE_PID__SAMPLE_TIME 100

#define EXPIRATION_VALVE_PID__DEFAULT_PROPORTIONAL_GAIN 0.0000011
#define EXPIRATION_VALVE_PID__DEFAULT_DERIVATIVE_GAIN   0.00000005
#define EXPIRATION_VALVE_PID__DEFAULT_INTEGRAL_GAIN     0.0000000

#define EXPIRATION_VALVE_PID__INHALE_RAMP_PROPORTIONAL_GAIN EXPIRATION_VALVE_PID__DEFAULT_PROPORTIONAL_GAIN
#define EXPIRATION_VALVE_PID__INHALE_RAMP_DERIVATIVE_GAIN   EXPIRATION_VALVE_PID__DEFAULT_DERIVATIVE_GAIN
#define EXPIRATION_VALVE_PID__INHALE_RAMP_INTEGRAL_GAIN     EXPIRATION_VALVE_PID__DEFAULT_INTEGRAL_GAIN

#define EXPIRATION_VALVE_PID__INHALE_HOLD_PROPORTIONAL_GAIN EXPIRATION_VALVE_PID__DEFAULT_PROPORTIONAL_GAIN
#define EXPIRATION_VALVE_PID__INHALE_HOLD_INTEGRAL_GAIN     EXPIRATION_VALVE_PID__DEFAULT_DERIVATIVE_GAIN
#define EXPIRATION_VALVE_PID__INHALE_HOLD_DERIVATIVE_GAIN   EXPIRATION_VALVE_PID__DEFAULT_INTEGRAL_GAIN

#define EXPIRATION_VALVE_PID__EXHALE_PROPORTIONAL_GAIN EXPIRATION_VALVE_PID__DEFAULT_PROPORTIONAL_GAIN
#define EXPIRATION_VALVE_PID__EXHALE_INTEGRAL_GAIN     EXPIRATION_VALVE_PID__DEFAULT_DERIVATIVE_GAIN
#define EXPIRATION_VALVE_PID__EXHALE_DERIVATIVE_GAIN   EXPIRATION_VALVE_PID__DEFAULT_INTEGRAL_GAIN
#define BREATHCYCLE__MINIMUM_PEEP__CENTIMETERSH2O 5.0
#pragma endregion

// I2C Multiplexer Settings
#pragma region
#define I2C_MULTIPLEXER__ADDRESS 0x70
#pragma endregion

#pragma region
#define DHLR_PRESSURE_SENSOR__DEFAULT_READING_TYPE AllSensors_DLHR::MeasurementType::AVERAGE2
#pragma endregion

#endif
