// List of Settings and constants for each subsystem
// Format as #define [SUB_SYSTEM]__[PARAMETER]__[UNIT]
//
// Avoid the use of abbreviations wherever possible
//
// For example:
// #define ENCODER_KNOB__NUMSTEPS 24
// #define ENCODER_KNOB__DISTANCEPERSTEP_MILLIMETERS 1.5
// #define HEATER_PID_LOOP__PROPORTIONAL_GAIN 0.000043


#ifndef _VENTILATOR_CONFIG_H_
#define _VENTILATOR_CONFIG_H_

#define SYSTEM__STARTUP_DELAY__MILLISECONDS 5000
#define SYSTEM__SERIAL_DEBUG__STATEMACHINE true
#define SYSTEM__SERIAL_DEBUG__BAUD_RATE 115200

#define BREATHCYCLE__MINIMUM_PEEP__CENTIMETERSH2O 5.0

#define BREATHCYCLE__DEFAULT_PEEP__CENTIMETERSH2O 5.0
#define BREATHCYCLE__DEFAULT_PIP__CENTIMETERSH2O 30.0
#define BREATHCYCLE__DEFAULT_INHALE_DURATION__MILLISECONDS 1000
#define BREATHCYCLE__DEFAULT_INHALE_RAMP_DURATION__MILLISECONDS 500
#define BREATHCYCLE__DEFAULT_EXHALE_DURATION__MILLISECONDS 3000
#define BREATHCYCLE__DEFAULT_CYCLE_DURATION__MILLISECONDS (BREATHCYCLE__DEFAULT_INHALE_DURATION__MILLISECONDS+BREATHCYCLE__DEFAULT_EXHALE_DURATION__MILLISECONDS)

#endif
